name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test using an iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set scheme
        run: |
          scheme=$(xcodebuild -list -json | jq -r '.projects[0].schemes[0]' 2>/dev/null || echo "DebToIPA")
          echo "SCHEME=$scheme" >> $GITHUB_ENV

      - name: Build
        env:
          platform: iOS
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE "iPhone.*?[^\\(]+" | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          if [ -z "$device" ]; then
            echo "No suitable simulator device found."
            exit 1
          fi
          file_to_build=$(ls -1 | grep -i "\.xcworkspace$\|\.xcodeproj$" | head -1)
          if [ -z "$file_to_build" ]; then
            echo "No valid Xcode project/workspace file present."
            exit 1
          fi
          xcodebuild build-for-testing -scheme "$SCHEME" -destination "platform=$platform,name=$device"

      - name: Test
        env:
          platform: iOS
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE "iPhone.*?[^\\(]+" | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          if [ -z "$device" ]; then
            echo "No suitable simulator device found."
            exit 1
          fi
          file_to_build=$(ls -1 | grep -i "\.xcworkspace$\|\.xcodeproj$" | head -1)
          if [ -z "$file_to_build" ]; then
            echo "No valid Xcode project/workspace file present."
            exit 1
          fi
          xcodebuild test-without-building -scheme "$SCHEME" -destination "platform=$platform,name=$device"
